apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::235028800035:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FF0MXMKTRJKB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::235028800035:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-14T02:44:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1736"
  uid: cf9eee5c-c2e4-49e4-8f14-0c9cb1608953
